### ISSUE TITLE
Holistic AI courses 

### ISSUE THREAD

**Issue by fatmaf** [PakistanAI/Educational_guide#3]
Looks like this is missing holistic AI courses such as https://open.ed.ac.uk/artificial-intelligence-planning/ and https://eu.udacity.com/course/intro-to-artificial-intelligence--cs271 
I was going to fork and add them but the descriptions there are fairly detailed (which I dont think I can do at this point) so just wanted to put this out there.

**Comment by anasayubi** [comment]
Good point. Thanks for adding in the courses!
